"""Report writer for parsing vulnerability measurement.

Generates a dated report with the schema defined in the plan plus a ranked
vulnerability summary.
"""

from __future__ import annotations

import os
from datetime import date
from pathlib import Path
from typing import Any

from tests.perf.harness import MeasurementResult


def generate_report(
    rows: list[MeasurementResult],
    output_path: str | Path | None = None,
    report_date: date | None = None,
) -> str:
    """Generate a parsing vulnerability report from measurement rows.

    Args:
        rows: List of MeasurementResult from the perf tests.
        output_path: Path to write the report. If None, uses default naming.
        report_date: Date for the report. If None, uses today's date.

    Returns:
        The path to the generated report.
    """
    if report_date is None:
        report_date = date.today()

    if output_path is None:
        output_path = Path("reports") / f"parsing-vulnerability-{report_date.isoformat()}.md"
    else:
        output_path = Path(output_path)

    # Ensure the reports directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate the report content
    content = _format_report(rows, report_date)

    # Write the report
    output_path.write_text(content)

    return str(output_path)


def _format_report(rows: list[MeasurementResult], report_date: date) -> str:
    """Format the report content."""
    lines: list[str] = []

    # Header
    lines.append(f"# Parsing Vulnerability Report — {report_date.isoformat()}")
    lines.append("")
    lines.append("This report was generated by the opt-in performance harness.")
    lines.append("")
    lines.append("## Configuration")
    lines.append("")
    lines.append(f"- **Budget:** {os.environ.get('PARSING_BUDGET_MS', '100')} ms")
    lines.append(f"- **Scaling ratio max:** {os.environ.get('PARSING_SCALING_RATIO_MAX', '3.0')}")
    lines.append("")

    # Summary statistics
    total_rows = len(rows)
    pass_count = sum(1 for r in rows if r.outcome == "pass")
    budget_exceeded = sum(1 for r in rows if r.outcome == "budget_exceeded")
    superlinear = sum(1 for r in rows if r.outcome == "superlinear")
    allocation_exceeded = sum(1 for r in rows if r.outcome == "allocation_exceeded")
    errors = sum(1 for r in rows if r.outcome == "error")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total rows:** {total_rows}")
    lines.append(f"- **Pass:** {pass_count}")
    lines.append(f"- **Budget exceeded:** {budget_exceeded}")
    lines.append(f"- **Superlinear:** {superlinear}")
    lines.append(f"- **Allocation exceeded:** {allocation_exceeded}")
    lines.append(f"- **Errors:** {errors}")
    lines.append("")

    # Ranked vulnerability summary
    vulnerabilities = [r for r in rows if r.outcome != "pass"]
    if vulnerabilities:
        lines.append("## Ranked Vulnerabilities")
        lines.append("")
        lines.append("Vulnerabilities are ranked by outcome severity, largest scaling ratio, and peak allocation.")
        lines.append("")
        lines.append("| Rank | Function | Family | Size | Outcome | Median (ms) | Ratio | Peak (bytes) |")
        lines.append("|---|---|---|---|---|---|---|---|")

        # Sort by severity (error > allocation_exceeded > superlinear > budget_exceeded)
        severity_order = {"error": 0, "allocation_exceeded": 1, "superlinear": 2, "budget_exceeded": 3}
        vulnerabilities.sort(
            key=lambda r: (
                severity_order.get(r.outcome, 4),
                -(r.scaling_ratio or 0),
                -r.peak_allocated_bytes,
            )
        )

        for i, row in enumerate(vulnerabilities, 1):
            ratio_str = f"{row.scaling_ratio:.2f}" if row.scaling_ratio is not None else "-"
            lines.append(
                f"| {i} | {row.function} | {row.family} | {row.size} | {row.outcome} | "
                f"{row.elapsed_median_ms:.2f} | {ratio_str} | {row.peak_allocated_bytes} |"
            )
        lines.append("")
    else:
        lines.append("## Vulnerabilities")
        lines.append("")
        lines.append("No vulnerabilities detected.")
        lines.append("")

    # Detailed rows
    lines.append("## Detailed Results")
    lines.append("")
    lines.append(
        "| Function | Wrapper | Family | Size | Median (ms) | Raw (ms) | Peak (bytes) | Outcome | Ratio | Exception |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|")

    for row in rows:
        raw_str = ", ".join(f"{t:.2f}" for t in row.raw_ms)
        ratio_str = f"{row.scaling_ratio:.2f}" if row.scaling_ratio is not None else "-"
        exception_str = row.exception_text[:50] + "..." if len(row.exception_text) > 50 else row.exception_text
        lines.append(
            f"| {row.function} | {row.wrapper_name} | {row.family} | {row.size} | "
            f"{row.elapsed_median_ms:.2f} | [{raw_str}] | {row.peak_allocated_bytes} | "
            f"{row.outcome} | {ratio_str} | {exception_str} |"
        )
    lines.append("")

    # Threshold recommendations for Plan 1
    lines.append("## Threshold Recommendations for Plan 1")
    lines.append("")
    lines.append("These values are derived from the measurement results above.")
    lines.append("")

    # Calculate recommended thresholds based on the data
    # For each function, find the maximum size that passes
    function_max_pass_size: dict[str, int] = {}
    for row in rows:
        if row.outcome == "pass":
            current_max = function_max_pass_size.get(row.function, 0)
            if row.size > current_max:
                function_max_pass_size[row.function] = row.size

    lines.append("| Function | Max Passing Size | Recommended Limit |")
    lines.append("|---|---|---|")
    for func, max_size in sorted(function_max_pass_size.items()):
        # Recommend a limit that is the max passing size or a reasonable default
        recommended = max_size if max_size > 0 else 1024
        lines.append(f"| {func} | {max_size} | {recommended} |")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by `tests/perf/report.py`*")
    lines.append("")
    lines.append("**Note:** Strict performance failures are opt-in and are not part of `make test`")
    lines.append("until a future plan changes that policy.")

    return "\n".join(lines)


def load_rows_from_modules() -> list[MeasurementResult]:
    """Load all collected rows from the perf test modules."""
    rows: list[MeasurementResult] = []

    # Import and collect from each module
    try:
        from tests.perf.test_parsing_scaling import get_collected_rows

        rows.extend(get_collected_rows())
    except ImportError:
        pass

    try:
        from tests.perf.test_regex_backtracking import get_collected_rows

        rows.extend(get_collected_rows())
    except ImportError:
        pass

    try:
        from tests.perf.test_decode_amplification import get_collected_rows

        rows.extend(get_collected_rows())
    except ImportError:
        pass

    try:
        from tests.perf.test_container_paths import get_collected_rows

        rows.extend(get_collected_rows())
    except ImportError:
        pass

    return rows
